### ISSUE TITLE
Using .setup() breaks suites that use scoped variables

### ISSUE THREAD

**Issue by adrian-moisa** [bestiejs/benchmark.js#114]
I use `require.js` for setting up a big collection of app modules benchmarks. Let's say that currently I am benchmarking one of the functions from an `utils` module. 

I don't understand why I can't use the `utils` variable (argument from an AMD module) in the second test. Can the use of global `_utils` be avoided at all? I have a lot of modules being tested and I don't want a flood of globals. It increases the chance of benchmarks failing because of globals colliding. I expect to have hundreds of suites running in sequence.

	//'use strict'; // Cannot use strict
	define(['Benchmark', 'utils' ], function (Benchmark, utils) {

		g_utils = utils; // global utils
		var suite = new Benchmark.Suite('utils');

		suite.add('parseJSON() - Empty', {
			fn: function () {
				// utils is resolved just fine 
				utils.parseJSON({});
			}
		});
		
		suite.add('parseJSON() - Empty', {
			fn: function () {
				// Cannot use utils, suite throws error
				g_utils.parseJSON(object);
			},
			setup: function () {
				var object = {};
			}
		});
	});

This is the error message the second function raises:

	 ReferenceError: utils is not defined 
	 at Benchmark.define.amd.uid1452503799783createFunction [as compiled] (<anonymous>:2:61) 
	 at clock (http://localhost/qualia/src/libs/benchmark/benchmark.js:2515:32) 
	 at clock (http://localhost/qualia/src/libs/benchmark/benchmark.js:2723:18) 
	 at cycle (http://localhost/qualia/src/libs/benchmark/benchmark.js:2913:47) 
	 at Benchmark.run (http://localhost/qualia/src/libs/benchmark/benchmark.js:3021:11) 
	 at execute (http://localhost/qualia/src/libs/benchmark/benchmark.js:1700:81)

**Comment by jdalton** [comment]
Which version of benchmark.js are you using?

**Comment by adrian-moisa** [comment]
Huh, I thought I have 2.0 but it's 1.0. I used bower without checking wich version was downloaded. Does this behavior change in 2.0 ?

**Comment by jdalton** [comment]
Yes. This should be resolved with v2. Let me know if it's not and I'll reopen.

**Comment by adrian-moisa** [comment]
Yes, it's fixed. Thank you!

**Comment by jdalton** [comment]
Rock!

**Comment by adrian-moisa** [comment]
Seems I still need to setup globals if I am using `.teardown()`. I usually don't use teardown, so it's not a big issue for me, but I thought this behavior should be mentioned.

**Comment by Soreine** [comment]
I still see this issue, using `v2.1.1`. Maybe I'm missing something. I have looked at other issues dealing with the scopes, setup, and Node tricky mix, but I haven't found a solution to this.

Here is a sample that does not work as of `v2.1.1`:

```js
const Benchmark = require('benchmark')

const suite = new Benchmark.Suite()

for (let foo of ['bar', 'baz']) {
    const findFoo = `Find ${foo} in this string`

    // This works, foo and findFoo are defined
    suite.add({
        name: foo,

        fn() {
            findFoo.indexOf(foo)
        }
    })

    // This does not work, foo and findFoo are undefined
    suite.add({
        name: foo,

        setup() {
            // Accessing foo here breaks the scope
            console.log('Accessing foo in setup', foo)
        },

        fn() {
            findFoo.indexOf(foo)
        }
    })
}

suite
.on('cycle', event => console.log(String(event.target)))
.on('error', event => console.log(event.target.error))
.run({ async: true })
```

Output:

```
bar x 9,383,439 ops/sec ±0.82% (81 runs sampled)
ReferenceError: foo is not defined
    ...
bar:
baz x 9,426,202 ops/sec ±0.70% (87 runs sampled)
ReferenceError: foo is not defined
    ...
baz:
```

I'm okay with using globals if really needed... But I can't make global some variables that are inherentely local and specific to a benchmark
